# Generated by Django 4.0.4 on 2022-08-06 11:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_snack_delete_snack1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snack',
            new_name='Book',
        ),
    ]
