# Generated by Django 4.0.4 on 2022-08-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_snack_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_title',
        ),
    ]
